# Stage 1: Build
FROM golang:latest AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY .env .env
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o apidanadesa .

# Stage 2: Run (super minimal)
FROM scratch

WORKDIR /app
COPY --from=builder /app/apidanadesa .

EXPOSE 8080
ENTRYPOINT ["./apidanadesa"]
