services:
  # Aplikasi Go (backend)
  app:
    build: .
    container_name: go_app_api_dana_desa
    ports:
      - "8004:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/tmp
      - ./public:/app/public
    restart: always
    networks:
      - mynetwork

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_golang
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - mynetwork

  # Database MySQL
  db:
    image: mysql:5.7
    container_name: db_dana_desa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_dana_desa
      MYSQL_USER: zayndev
      MYSQL_PASSWORD: Eren1510_
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  # PhpMyAdmin untuk mempermudah manajemen database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=zayndev
      - PMA_PASSWORD=Eren1510_
    ports:
      - "8087:80"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
